修正 do_query 函数的缺陷。该代码有一定概率漏掉处理 Z 消息。导致后来对 handle 的调用因 handle->state 的状态不正确而出错。
用例：
create table master(f1 int primary key);
create table slave(f1 int references master deferrable);
insert into master values(1);
insert into slave values(1);
insert into slave values(2);
create function trap_foreign_key(int) returns int as 4449
begin
    begin   -- start a subtransaction
        insert into slave values();
    exception
        when foreign_key_violation then
            raise notice 'caught foreign_key_violation';
            return 0;
    end;
    return 1;
end4449 language plpgsql;

select trap_foreign_key(2);

多次执行 select trap_foreign_key(2) 可能会产生下列错误。

postgres=# select trap_foreign_key(2);
NOTICE:  caught foreign_key_violation
ERROR:  failed to send COMMIT command to node

Conflicts:
	src/backend/pgxc/pool/execRemote.c